services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    hostname: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    #ports:
    #  - 11434:11434
    environment:
      OLLAMA_MODEL_PULL: ${OLLAMA_MODEL_PULL:-deepseek-r1:7b}
    volumes:
      - ./ollama:/root/.ollama
      - ./scripts/ollama-entry.sh:/entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  # https://localhost - Open WebUI
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    hostname: openwebui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.entrypoints=https"
      - "traefik.http.routers.openwebui.rule=PathPrefix(`/`)"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
      - "traefik.http.services.openwebui.loadbalancer.server.scheme=http"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    #ports:
    #  - 3000:8080
    environment:
      CORS_ALLOW_ORIGIN: https://localhost
      ENABLE_OPENAI_API: false
      ENABLE_SIGNUP: false
      OLLAMA_BASE_URL: http://ollama:11434
      USE_CUDA_DOCKER: true
      WEBUI_URL: https://localhost
    volumes:
      - ./openwebui:/app/backend/data
    restart: unless-stopped

  # https://localhost:8443 - Traefik dashboard
  traefik:
    image: traefik
    container_name: traefik
    hostname: traefik
    command:
      - "--api.dashboard=true"
      - "--serversTransport.insecureSkipVerify=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.http.tls=true"
      - "--entrypoints.https.http3=true"
      - "--entrypoints.https-alt.address=:8443"
      - "--entrypoints.https-alt.http.tls=true"
      - "--entrypoints.https-alt.http3=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=https-alt"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/`)"
      - "traefik.http.routers.traefik.service=api@internal"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
        protocol: tcp
      - target: 443
        published: 443
        mode: host
        protocol: udp
      - target: 8443
        published: 8443
        mode: host
        protocol: tcp
      - target: 8443
        published: 8443
        mode: host
        protocol: udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
